import type { PlanetData } from './types'

export const PLANETS: PlanetData[] = [
  {
    id: 'mercury',
    name: 'Mercury',
    radius: 0.28,
    orbitRadius: 5.5,
    orbitSpeed: 0.04,
    rotationSpeed: 0.01,
    color: '#b5b5b5',
    emissive: '#1a1a1a',
    roughness: 0.9,
    metalness: 0.1,
    description: 'The smallest planet and closest to the Sun, with extreme temperature swings.',
    distanceFromSun: '57.9M km',
    dayLength: '1,408 hrs',
    yearLength: '88 days',
    gravity: '3.7 m/s²',
    radiusKm: '2,439 km',
    moons: 0,
    interestingFact: 'A day on Mercury is longer than its year.',
  },
  {
    id: 'venus',
    name: 'Venus',
    radius: 0.52,
    orbitRadius: 8.5,
    orbitSpeed: 0.025,
    rotationSpeed: 0.005,
    color: '#e8c97a',
    emissive: '#3d2a00',
    roughness: 0.8,
    metalness: 0.1,
    atmosphereColor: '#e8d88a',
    description: 'The hottest planet with a thick toxic atmosphere and crushing pressure.',
    distanceFromSun: '108.2M km',
    dayLength: '5,832 hrs',
    yearLength: '225 days',
    gravity: '8.87 m/s²',
    radiusKm: '6,051 km',
    moons: 0,
    interestingFact: 'Venus rotates backwards — the Sun rises in the west.',
  },
  {
    id: 'earth',
    name: 'Earth',
    radius: 0.58,
    orbitRadius: 12.0,
    orbitSpeed: 0.02,
    rotationSpeed: 0.02,
    color: '#2a6edb',
    emissive: '#001133',
    roughness: 0.7,
    metalness: 0.1,
    hasMoon: true,
    atmosphereColor: '#4499ff',
    description: 'Our home — the only known planet harboring life in the universe.',
    distanceFromSun: '149.6M km',
    dayLength: '24 hrs',
    yearLength: '365 days',
    gravity: '9.81 m/s²',
    radiusKm: '6,371 km',
    moons: 1,
    interestingFact: 'Earth is the densest planet in the Solar System.',
  },
  {
    id: 'mars',
    name: 'Mars',
    radius: 0.42,
    orbitRadius: 16.5,
    orbitSpeed: 0.015,
    rotationSpeed: 0.018,
    color: '#c1440e',
    emissive: '#3d0a00',
    roughness: 0.95,
    metalness: 0.05,
    atmosphereColor: '#e05520',
    description: 'The Red Planet with the tallest volcano and deepest canyon in the Solar System.',
    distanceFromSun: '227.9M km',
    dayLength: '24.6 hrs',
    yearLength: '687 days',
    gravity: '3.72 m/s²',
    radiusKm: '3,389 km',
    moons: 2,
    interestingFact: 'Olympus Mons on Mars is 3x taller than Mount Everest.',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    radius: 1.4,
    orbitRadius: 24.0,
    orbitSpeed: 0.008,
    rotationSpeed: 0.04,
    color: '#c88b3a',
    emissive: '#1a0500',
    roughness: 0.6,
    metalness: 0.2,
    description: 'The largest planet — a gas giant with the iconic Great Red Spot storm.',
    distanceFromSun: '778.5M km',
    dayLength: '9.9 hrs',
    yearLength: '12 years',
    gravity: '24.79 m/s²',
    radiusKm: '69,911 km',
    moons: 95,
    interestingFact: 'The Great Red Spot has been raging for over 350 years.',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    radius: 1.2,
    orbitRadius: 33.0,
    orbitSpeed: 0.005,
    rotationSpeed: 0.038,
    color: '#e4d191',
    emissive: '#1a1200',
    roughness: 0.6,
    metalness: 0.1,
    hasRings: true,
    description: 'The ringed jewel of the Solar System — a gas giant less dense than water.',
    distanceFromSun: '1.43B km',
    dayLength: '10.7 hrs',
    yearLength: '29 years',
    gravity: '10.44 m/s²',
    radiusKm: '58,232 km',
    moons: 146,
    interestingFact: 'Saturn is so light it would float in water.',
  },
  {
    id: 'uranus',
    name: 'Uranus',
    radius: 0.88,
    orbitRadius: 42.0,
    orbitSpeed: 0.003,
    rotationSpeed: 0.025,
    color: '#7de8e8',
    emissive: '#003333',
    roughness: 0.5,
    metalness: 0.2,
    atmosphereColor: '#aaffee',
    description: 'An ice giant that rotates on its side with a dramatic 98° axial tilt.',
    distanceFromSun: '2.87B km',
    dayLength: '17.2 hrs',
    yearLength: '84 years',
    gravity: '8.69 m/s²',
    radiusKm: '25,362 km',
    moons: 28,
    interestingFact: 'Uranus rolls around the Sun completely on its side.',
  },
  {
    id: 'neptune',
    name: 'Neptune',
    radius: 0.82,
    orbitRadius: 52.0,
    orbitSpeed: 0.002,
    rotationSpeed: 0.03,
    color: '#3f54ba',
    emissive: '#000a33',
    roughness: 0.5,
    metalness: 0.2,
    atmosphereColor: '#6688ff',
    description: 'The windiest planet with supersonic storms reaching 2,100 km/h.',
    distanceFromSun: '4.5B km',
    dayLength: '16.1 hrs',
    yearLength: '165 years',
    gravity: '11.15 m/s²',
    radiusKm: '24,622 km',
    moons: 16,
    interestingFact: 'Neptune was predicted mathematically before it was seen.',
  },
]

export const SUN_DATA = {
  id: 'sun',
  name: 'Sun',
  radius: 2.8,
  color: '#fff3a8',
  emissive: '#ff6600',
  description: 'The star at the center of our Solar System',
}
