import type { PlanetData } from './types'

export const PLANETS: PlanetData[] = [
  {
    id: 'mercury',
    name: 'Mercury',
    radius: 0.65,
    orbitRadius: 8.0,
    orbitSpeed: 0.04,
    rotationSpeed: 0.01,
    color: '#c8c8c8',
    emissive: '#333333',
    roughness: 0.9,
    metalness: 0.1,
    description: 'Closest planet to the Sun',
    distanceFromSun: '57.9M km',
    dayLength: '1,408 hours',
    yearLength: '88 days',
    diameter: '4,879 km', gravity: '3.7 m/s²', orbitalPeriod: '88 days', moonCount: '0', fact: 'Mercury has no atmosphere.',
  },
  {
    id: 'venus',
    name: 'Venus',
    radius: 1.0,
    orbitRadius: 13.0,
    orbitSpeed: 0.025,
    rotationSpeed: 0.005,
    color: '#f0d060',
    emissive: '#5a3a00',
    roughness: 0.8,
    metalness: 0.1,
    atmosphereColor: '#f0d070',
    description: 'Hottest planet in the Solar System',
    distanceFromSun: '108.2M km',
    dayLength: '5,832 hours',
    yearLength: '225 days',
    diameter: '12,104 km', gravity: '8.9 m/s²', orbitalPeriod: '225 days', moonCount: '0', fact: 'Venus rotates backward (retrograde).',
  },
  {
    id: 'earth',
    name: 'Earth',
    radius: 1.05,
    orbitRadius: 18.5,
    orbitSpeed: 0.02,
    rotationSpeed: 0.02,
    color: '#3a8aff',
    emissive: '#001855',
    roughness: 0.7,
    metalness: 0.1,
    hasMoon: true,
    atmosphereColor: '#66aaff',
    description: 'Our home planet',
    distanceFromSun: '149.6M km',
    dayLength: '24 hours',
    yearLength: '365 days',
    diameter: '12,742 km', gravity: '9.8 m/s²', orbitalPeriod: '365.25 days', moonCount: '1', fact: 'Earth is 71% water.',
  },
  {
    id: 'mars',
    name: 'Mars',
    radius: 0.8,
    orbitRadius: 26.0,
    orbitSpeed: 0.015,
    rotationSpeed: 0.018,
    color: '#e05015',
    emissive: '#500800',
    roughness: 0.95,
    metalness: 0.05,
    atmosphereColor: '#f06530',
    description: 'The Red Planet',
    distanceFromSun: '227.9M km',
    dayLength: '24.6 hours',
    yearLength: '687 days',
    diameter: '6,779 km', gravity: '3.7 m/s²', orbitalPeriod: '687 days', moonCount: '2', fact: 'Mars has the largest volcano in the solar system.',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    radius: 2.2,
    orbitRadius: 38.0,
    orbitSpeed: 0.008,
    rotationSpeed: 0.04,
    color: '#d4a060',
    emissive: '#2a0e00',
    roughness: 0.6,
    metalness: 0.2,
    description: 'Largest planet in the Solar System',
    distanceFromSun: '778.5M km',
    dayLength: '9.9 hours',
    yearLength: '12 years',
    diameter: '139,820 km', gravity: '24.8 m/s²', orbitalPeriod: '12 years', moonCount: '95', fact: 'Jupiter has a massive storm called the Great Red Spot.',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    radius: 1.95,
    orbitRadius: 52.0,
    orbitSpeed: 0.005,
    rotationSpeed: 0.038,
    color: '#ead888',
    emissive: '#2a1e00',
    roughness: 0.6,
    metalness: 0.1,
    hasRings: true,
    description: 'Planet with iconic ring system',
    distanceFromSun: '1.43B km',
    dayLength: '10.7 hours',
    yearLength: '29 years',
    diameter: '116,460 km', gravity: '10.4 m/s²', orbitalPeriod: '29 years', moonCount: '146', fact: 'Saturn could float on water due to its low density.',
  },
  {
    id: 'uranus',
    name: 'Uranus',
    radius: 1.5,
    orbitRadius: 66.0,
    orbitSpeed: 0.003,
    rotationSpeed: 0.025,
    color: '#55dddd',
    emissive: '#004444',
    roughness: 0.5,
    metalness: 0.2,
    atmosphereColor: '#88ffee',
    description: 'Ice giant with tilted axis',
    distanceFromSun: '2.87B km',
    dayLength: '17.2 hours',
    yearLength: '84 years',
    diameter: '50,724 km', gravity: '8.7 m/s²', orbitalPeriod: '84 years', moonCount: '28', fact: 'Uranus rotates on its side.',
  },
  {
    id: 'neptune',
    name: 'Neptune',
    radius: 1.45,
    orbitRadius: 80.0,
    orbitSpeed: 0.002,
    rotationSpeed: 0.03,
    color: '#4466ee',
    emissive: '#000e44',
    roughness: 0.5,
    metalness: 0.2,
    atmosphereColor: '#8899ff',
    description: 'Farthest planet from the Sun',
    distanceFromSun: '4.5B km',
    dayLength: '16.1 hours',
    yearLength: '165 years',
    diameter: '49,244 km', gravity: '11.2 m/s²', orbitalPeriod: '165 years', moonCount: '16', fact: 'Neptune has the fastest winds in the solar system.',
  },
]

export const SUN_DATA = {
  id: 'sun',
  name: 'Sun',
  radius: 5.0,
  color: '#fff3a8',
  emissive: '#ff6600',
  description: 'The star at the center of our Solar System',
}
