import type { PlanetData } from './types'

export const PLANETS: PlanetData[] = [
  {
    id: 'mercury',
    name: 'Mercury',
    radius: 0.18,
    orbitRadius: 3.5,
    orbitSpeed: 0.04,
    rotationSpeed: 0.01,
    color: '#b5b5b5',
    emissive: '#1a1a1a',
    roughness: 0.9,
    metalness: 0.1,
    description: 'Closest planet to the Sun',
    distanceFromSun: '57.9M km',
    dayLength: '1,408 hours',
    yearLength: '88 days',
  },
  {
    id: 'venus',
    name: 'Venus',
    radius: 0.35,
    orbitRadius: 5.5,
    orbitSpeed: 0.025,
    rotationSpeed: 0.005,
    color: '#e8c97a',
    emissive: '#3d2a00',
    roughness: 0.8,
    metalness: 0.1,
    atmosphereColor: '#e8d88a',
    description: 'Hottest planet in the Solar System',
    distanceFromSun: '108.2M km',
    dayLength: '5,832 hours',
    yearLength: '225 days',
  },
  {
    id: 'earth',
    name: 'Earth',
    radius: 0.4,
    orbitRadius: 8.0,
    orbitSpeed: 0.02,
    rotationSpeed: 0.02,
    color: '#2a6edb',
    emissive: '#001133',
    roughness: 0.7,
    metalness: 0.1,
    hasMoon: true,
    atmosphereColor: '#4499ff',
    description: 'Our home planet',
    distanceFromSun: '149.6M km',
    dayLength: '24 hours',
    yearLength: '365 days',
  },
  {
    id: 'mars',
    name: 'Mars',
    radius: 0.3,
    orbitRadius: 11.0,
    orbitSpeed: 0.015,
    rotationSpeed: 0.018,
    color: '#c1440e',
    emissive: '#3d0a00',
    roughness: 0.95,
    metalness: 0.05,
    atmosphereColor: '#e05520',
    description: 'The Red Planet',
    distanceFromSun: '227.9M km',
    dayLength: '24.6 hours',
    yearLength: '687 days',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    radius: 1.0,
    orbitRadius: 16.0,
    orbitSpeed: 0.008,
    rotationSpeed: 0.04,
    color: '#c88b3a',
    emissive: '#1a0500',
    roughness: 0.6,
    metalness: 0.2,
    description: 'Largest planet in the Solar System',
    distanceFromSun: '778.5M km',
    dayLength: '9.9 hours',
    yearLength: '12 years',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    radius: 0.85,
    orbitRadius: 22.0,
    orbitSpeed: 0.005,
    rotationSpeed: 0.038,
    color: '#e4d191',
    emissive: '#1a1200',
    roughness: 0.6,
    metalness: 0.1,
    hasRings: true,
    description: 'Planet with iconic ring system',
    distanceFromSun: '1.43B km',
    dayLength: '10.7 hours',
    yearLength: '29 years',
  },
  {
    id: 'uranus',
    name: 'Uranus',
    radius: 0.6,
    orbitRadius: 28.0,
    orbitSpeed: 0.003,
    rotationSpeed: 0.025,
    color: '#7de8e8',
    emissive: '#003333',
    roughness: 0.5,
    metalness: 0.2,
    atmosphereColor: '#aaffee',
    description: 'Ice giant with tilted axis',
    distanceFromSun: '2.87B km',
    dayLength: '17.2 hours',
    yearLength: '84 years',
  },
  {
    id: 'neptune',
    name: 'Neptune',
    radius: 0.55,
    orbitRadius: 34.0,
    orbitSpeed: 0.002,
    rotationSpeed: 0.03,
    color: '#3f54ba',
    emissive: '#000a33',
    roughness: 0.5,
    metalness: 0.2,
    atmosphereColor: '#6688ff',
    description: 'Farthest planet from the Sun',
    distanceFromSun: '4.5B km',
    dayLength: '16.1 hours',
    yearLength: '165 years',
  },
]

export const SUN_DATA = {
  id: 'sun',
  name: 'Sun',
  radius: 2.0,
  color: '#fff3a8',
  emissive: '#ff6600',
  description: 'The star at the center of our Solar System',
}
